export const TOUR_LIST_REQUEST = "TOUR_LIST_REQUEST";
export const TOUR_LIST_SUCCESS = "TOUR_LIST_SUCCESS";
export const TOUR_LIST_FAIL = "TOUR_LIST_FAIL";

export const TOUR_DETAIL_REQUEST = "TOUR_DETAIL_REQUEST";
export const TOUR_DETAIL_SUCCESS = "TOUR_DETAIL_SUCCESS";
export const TOUR_DETAIL_FAIL = "TOUR_DETAIL_FAIL";